### ISSUE TITLE
Warning messages: 1: package ‘TOAST’ is not available (for R version 3.6.0) 

### ISSUE THREAD

**Issue by AgazW** [ziyili20/TOAST#1]
I tried to install the package using `BiocManager::install("TOAST")` and I already have `R 3.6` as needed for your package. But I get error saying `Warning messages: 1: package ‘TOAST’ is not available (for R version 3.6.0) `. Not sure what is going wrong. 

`[R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.3
Matrix products: default
BLAS:
/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib
Random number generation:
RNG:     Mersenne-Twister 
Normal:  Inversion 
Sample:  Rounding
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base
other attached packages:
[1] rtracklayer_1.43.3   GenomicRanges_1.36.0 GenomeInfoDb_1.20.0  IRanges_2.18.1      
[5] S4Vectors_0.22.0     BiocGenerics_0.30.0
loaded via a namespace (and not attached):
 [1] XVector_0.24.0              zlibbioc_1.30.0             GenomicAlignments_1.20.1
[4] BiocParallel_1.18.0         lattice_0.20-38             tools_3.6.0
[7] SummarizedExperiment_1.14.0 grid_3.6.0                  Biobase_2.44.0             
[10] matrixStats_0.54.0          Matrix_1.2-17               GenomeInfoDbData_1.2.1
[13] BiocManager_1.30.4          bitops_1.0-6                RCurl_1.95-4.12        
[16] DelayedArray_0.10.0         compiler_3.6.0              Biostrings_2.52.0          
[19] Rsamtools_2.0.0             XML_3.98-1.20 ](url)
[R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.3
Matrix products: default
BLAS:
/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib
Random number generation:
RNG:     Mersenne-Twister 
Normal:  Inversion 
Sample:  Rounding 
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] rtracklayer_1.43.3   GenomicRanges_1.36.0 GenomeInfoDb_1.20.0  IRanges_2.18.1      
[5] S4Vectors_0.22.0     BiocGenerics_0.30.0
loaded via a namespace (and not attached):
[1] XVector_0.24.0              zlibbioc_1.30.0             GenomicAlignments_1.20.1   
[4] BiocParallel_1.18.0         lattice_0.20-38             tools_3.6.0                
[7] SummarizedExperiment_1.14.0 grid_3.6.0                  Biobase_2.44.0             
[10] matrixStats_0.54.0          Matrix_1.2-17               GenomeInfoDbData_1.2.1     
[13] BiocManager_1.30.4          bitops_1.0-6                RCurl_1.95-4.12            
[16] DelayedArray_0.10.0         compiler_3.6.0              Biostrings_2.52.0          
[19] Rsamtools_2.0.0             XML_3.98-1.20 ](url)`

**Comment by ziyili20** [comment]
Hello, the TOAST is still in development version on Biocondcutor site (it takes some time to make a newly submitted package upgrade from development version). So the recommended installation code is:
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

# The following initializes usage of Bioc devel
BiocManager::install(version='devel')

BiocManager::install("TOAST")

Can you try this and let me know if still not work? I have updated the readme file to clarify this.

**Comment by AgazW** [comment]
Thank you for reaching out to me with the solution, however, I used GitHub to install your package. The output of your package shows different columns such as 'beta', 'effect_size', can you please some information about that on your GitHub page.

**Comment by ziyili20** [comment]
Hello, the beta is the cell type-specific gene expression (or DNA methylation) difference between two groups. For example, if you apply TOAST on gene expression data of cases and controls, beta will be the GE level difference between cases and controls. Effect size is calculated in TOAST by beta/(mu+beta/2), mu is the baseline expression in one group. Effect size intuitively compares the cell type-specific difference versus the base expression. We add beta/2 in the denominator, since mu can be very small for some cell type and makes the ratio not stable. Hope this helps.

**Comment by soueryw** [comment]
Hi, I am having the same issues in R 4.1 (Error: package ‘TOAST’ 1.8.3 was found, but >= 1.10.1 is required by ‘MuSiC’
Execution halted
ERROR: lazy loading failed for package ‘MuSiC’). 

See details below: 

> devtools::install_github('xuranw/MuSiC')
Downloading GitHub repo xuranw/MuSiC@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                          
2: CRAN packages only           
3: None                         
4: rlang (1.1.0 -> 1.1.1) [CRAN]
5: vctrs (0.5.1 -> 0.6.2) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 1
rlang (1.1.0 -> 1.1.1) [CRAN]
vctrs (0.5.1 -> 0.6.2) [CRAN]
Skipping 3 packages not available: SingleCellExperiment, Biobase, TOAST
Installing 2 packages: rlang, vctrs
Installing packages into ‘/usr3/graduate/soueryw/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/rlang_1.1.1.tar.gz'
Content type 'application/x-gzip' length 762533 bytes (744 KB)
==================================================
downloaded 744 KB

trying URL 'https://cran.rstudio.com/src/contrib/vctrs_0.6.2.tar.gz'
Content type 'application/x-gzip' length 964633 bytes (942 KB)
==================================================
downloaded 942 KB

ERROR: failed to lock directory ‘/usr3/graduate/soueryw/R/x86_64-pc-linux-gnu-library/4.1’ for modifying
Try removing ‘/usr3/graduate/soueryw/R/x86_64-pc-linux-gnu-library/4.1/00LOCK-rlang’
ERROR: failed to lock directory ‘/usr3/graduate/soueryw/R/x86_64-pc-linux-gnu-library/4.1’ for modifying
Try removing ‘/usr3/graduate/soueryw/R/x86_64-pc-linux-gnu-library/4.1/00LOCK-vctrs’

The downloaded source packages are in
	‘/scratch/187841.1.ood/Rtmp8ek7p5/downloaded_packages’
── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/scratch/187841.1.ood/Rtmp8ek7p5/remotes586030ae8371/xuranw-MuSiC-0a3e3af/DESCRIPTION’ ...
─  preparing ‘MuSiC’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘MuSiC_1.0.0.tar.gz’
   Warning in sprintf(gettext(fmt, domain = domain), ...) :
     one argument not used by format 'invalid uid value replaced by that for user 'nobody''
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning in sprintf(gettext(fmt, domain = domain), ...) :
     one argument not used by format 'invalid gid value replaced by that for user 'nobody''
   Warning: invalid gid value replaced by that for user 'nobody'
   
Installing package into ‘/usr3/graduate/soueryw/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package ‘MuSiC’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: package ‘TOAST’ 1.8.3 was found, but >= 1.10.1 is required by ‘MuSiC’
Execution halted
ERROR: lazy loading failed for package ‘MuSiC’
* removing ‘/usr3/graduate/soueryw/R/x86_64-pc-linux-gnu-library/4.1/MuSiC’
Warning messages:
1: In i.p(...) : installation of package ‘rlang’ had non-zero exit status
2: In i.p(...) : installation of package ‘vctrs’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘/scratch/187841.1.ood/Rtmp8ek7p5/file58607bb9ceae/MuSiC_1.0.0.tar.gz’ had non-zero exit status

**Comment by ziyili20** [comment]
I think you may need to re-install TOAST. When you instal MuSiC, it seems
TOAST was skipped as TOAST is from bioconductor, not CRAN. You can manually
install TOAST through:

if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("TOAST")
