### ISSUE TITLE
Error "Y should have dimension P (features) by N (samples)!" from fitModel

### ISSUE THREAD

**Issue by fumi-github** [ziyili20/TOAST#3]
Hi.
In fitModel.R, you write

  if (nrow(Y) < ncol(Y)) {
    stop("Y should have dimension P (features) by N (samples)!")
  }

In a situation like simulation, nrow(Y) could be small.
I guess the test should be

nrow(Design_out$design_matrix) != ncol(Y)

Thanks.

**Comment by ziyili20** [comment]
Yes! Thank you for the comment. I identified this issue too. In the new version of the package, I removed this checking step.
