### ISSUE TITLE
RNAseq preprocessing for TOAST

### ISSUE THREAD

**Issue by pawlorkarpinski** [ziyili20/TOAST#4]
Dear Ziyi,

What are your suggestions for preprocessing RNA-seq data to be used in TOAST for cell-specific DE?

Kind regards,

Pawel

**Comment by ziyili20** [comment]
Dear Pawel,

I believe the RNA-seq data should be aligned and normalized before using TOAST. Different from methods like DESeq2 which requires raw counts, TOAST does not do normalization thus sequencing depth should be normalized before the analysis. I used RNA-seq in FPKM format with TOAST before, but there is no definite answer for which is the best among FPKM, TPM or RPKM. Maybe this is something we should study in the future. Hope this helps.

Ziyi

**Comment by pawlorkarpinski** [comment]
Dear Ziyi,

Thank you for your answer! It clears a lot.

Warm regards,

Pawel
