### ISSUE TITLE
WGBS data of tissue samples 

### ISSUE THREAD

**Issue by Niinleslie** [ziyili20/TOAST#5]
Hi, ziyi
Can I apply TOAST to esitmate immune cell fractions of WGBS data from liver tumor tissues?
If so, how should I prepare the input data?

**Comment by ziyili20** [comment]
Hi Niinleslie,
Sorry for this late reply. Somehow I don't receive emails from Github recently. Feel free to email me at zli16@mdanderson.org if my answer does not solve your question.
TOAST currently does not have functions specifically for WGBS. The previously published Tsisal is mainly designed for DNA methylation array. There are two other existing methods that you can consider to apply on your WGBS data. First is methyICC (https://github.com/stephaniehicks/methylCC). Second is EpiDISH. The first method is applicable for WGBS data. The second one, although designed for DNA methylation array, has been applied to WGBS data before (https://www.thelancet.com/article/S2352-3964(18)30153-1/fulltext). 
Hope this helps.
